import React, { useState, useEffect } from 'react';
import { getReports, getReport, downloadReport, generateFullReport } from '../../services/adminService';

const ReportsView = () => {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [selectedReport, setSelectedReport] = useState(null);
  const [showModal, setShowModal] = useState(false);
  const [generateForm, setGenerateForm] = useState({
    type: 'weekly',
    period_start: '',
    period_end: '',
    format: 'json'
  });
  const [showGenerateModal, setShowGenerateModal] = useState(false);
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    loadReports();
  }, []);

  const loadReports = async () => {
    setLoading(true);
    try {
      const res = await getReports();
      setReports(res.data || []);
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to load reports');
    } finally {
      setLoading(false);
    }
  };

  const handleViewReport = async (id) => {
    setLoading(true);
    try {
      const res = await getReport(id);
      setSelectedReport(res.data);
      setShowModal(true);
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to load report');
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = async (id) => {
    try {
      const blob = await downloadReport(id);
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `report_${id}.${blob.type === 'application/json' ? 'json' : 'csv'}`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
    } catch (err) {
      setError('Failed to download report');
    }
  };

  const handleGenerateSubmit = async (e) => {
    e.preventDefault();
    if (!generateForm.period_start || !generateForm.period_end) {
      setError('Please select start and end dates');
      return;
    }
    setGenerating(true);
    try {
      const res = await generateFullReport(generateForm.type, generateForm.period_start, generateForm.period_end, generateForm.format);
      setError('');
      setShowGenerateModal(false);
      loadReports();
      alert('Report generated successfully');
    } catch (err) {
      setError(err.response?.data?.message || 'Generation failed');
    } finally {
      setGenerating(false);
    }
  };

  const renderReportData = (data) => {
    if (!data) return <p>No data</p>;
    if (typeof data === 'string') {
      try { data = JSON.parse(data); } catch(e) {}
    }
    return (
      <div>
        <h6>Summary</h6>
        <ul>
          <li>Total Vaccinations: {data.summary?.total_vaccinations || 0}</li>
          <li>Children Vaccinated: {data.summary?.total_children_vaccinated || 0}</li>
          <li>Missed Appointments: {data.summary?.missed_appointments || 0}</li>
        </ul>
        <h6>By Vaccine</h6>
        <table className="table table-sm">
          <thead><tr><th>Vaccine</th><th>Count</th></tr></thead>
          <tbody>
            {data.by_vaccine?.map((v, i) => <tr key={i}><td>{v.name}</td><td>{v.count}</td></tr>)}
          </tbody>
        </table>
      </div>
    );
  };

  return (
    <div>
      <div className="d-flex justify-content-between align-items-center mb-3">
        <h4>System Reports</h4>
        <button className="btn btn-success" onClick={() => { setShowGenerateModal(true); setError(''); }}>
          + Generate New Report
        </button>
      </div>

      {error && <div className="alert alert-danger">{error}</div>}

      {loading ? (
        <div className="text-center py-5"><div className="spinner-border text-primary"></div></div>
      ) : reports.length === 0 ? (
        <div className="alert alert-info">No reports available. Generate one using the button above.</div>
      ) : (
        <div className="table-responsive">
          <table className="table table-bordered table-hover">
            <thead className="table-light">
              <tr>
                <th>ID</th>
                <th>Type</th>
                <th>Period Start</th>
                <th>Period End</th>
                <th>Generated By</th>
                <th>Created At</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {reports.map(report => (
                <tr key={report.id}>
                  <td>{report.id}</td>
                  <td><span className="badge bg-info">{report.type}</span></td>
                  <td>{report.period_start} </td>
                  <td>{report.period_end} </td>
                  <td>{report.generated_by_name || `User ${report.generated_by}`}</td>
                  <td>{new Date(report.created_at).toLocaleString()}</td>
                  <td>
                    <button className="btn btn-sm btn-primary me-1" onClick={() => handleViewReport(report.id)}>👁️ View</button>
                    {report.file_path && <button className="btn btn-sm btn-secondary" onClick={() => handleDownload(report.id)}>⬇️ Download</button>}
                   </td>
                 </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* View Report Modal */}
      {showModal && selectedReport && (
        <div className="modal show d-block" tabIndex="-1" style={{ backgroundColor: 'rgba(0,0,0,0.5)' }}>
          <div className="modal-dialog modal-lg">
            <div className="modal-content">
              <div className="modal-header bg-primary text-white">
                <h5 className="modal-title">Report Details</h5>
                <button type="button" className="btn-close btn-close-white" onClick={() => setShowModal(false)}></button>
              </div>
              <div className="modal-body">
                <p><strong>Type:</strong> {selectedReport.type}</p>
                <p><strong>Period:</strong> {selectedReport.period_start} to {selectedReport.period_end}</p>
                <p><strong>Generated by:</strong> {selectedReport.generated_by_name}</p>
                <p><strong>Created at:</strong> {new Date(selectedReport.created_at).toLocaleString()}</p>
                <hr />
                {renderReportData(selectedReport.data)}
              </div>
              <div className="modal-footer">
                <button className="btn btn-secondary" onClick={() => setShowModal(false)}>Close</button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Generate Report Modal */}
      {showGenerateModal && (
        <div className="modal show d-block" tabIndex="-1" style={{ backgroundColor: 'rgba(0,0,0,0.5)' }}>
          <div className="modal-dialog">
            <div className="modal-content">
              <div className="modal-header bg-success text-white">
                <h5 className="modal-title">Generate System Report</h5>
                <button type="button" className="btn-close btn-close-white" onClick={() => setShowGenerateModal(false)}></button>
              </div>
              <form onSubmit={handleGenerateSubmit}>
                <div className="modal-body">
                  <div className="mb-3">
                    <label className="form-label">Report Type</label>
                    <select className="form-select" value={generateForm.type} onChange={e => setGenerateForm({...generateForm, type: e.target.value})}>
                      <option value="weekly">Weekly</option>
                      <option value="monthly">Monthly</option>
                    </select>
                  </div>
                  <div className="mb-3">
                    <label className="form-label">Start Date</label>
                    <input type="date" className="form-control" value={generateForm.period_start} onChange={e => setGenerateForm({...generateForm, period_start: e.target.value})} required />
                  </div>
                  <div className="mb-3">
                    <label className="form-label">End Date</label>
                    <input type="date" className="form-control" value={generateForm.period_end} onChange={e => setGenerateForm({...generateForm, period_end: e.target.value})} required />
                  </div>
                  <div className="mb-3">
                    <label className="form-label">Format</label>
                    <select className="form-select" value={generateForm.format} onChange={e => setGenerateForm({...generateForm, format: e.target.value})}>
                      <option value="json">JSON</option>
                      <option value="csv">CSV</option>
                      <option value="pdf">PDF</option>
                    </select>
                  </div>
                </div>
                <div className="modal-footer">
                  <button type="button" className="btn btn-secondary" onClick={() => setShowGenerateModal(false)}>Cancel</button>
                  <button type="submit" className="btn btn-success" disabled={generating}>
                    {generating ? <span className="spinner-border spinner-border-sm"></span> : 'Generate'}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ReportsView;